computer/computer/urls.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""
URL configuration for computer project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView, TemplateView


admin.site.site_header = _("computer administration")


urlpatterns = [
    path("", TemplateView.as_view(template_name="computer/chat.html"), name="chat"),
    path("admin/", admin.site.urls),
    path("api/", include("computer.api_urls")),
    path("profiles/", include("profiles.urls")),
    path("favicon.ico", RedirectView.as_view(url="/static/images/icon.png")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

computer/profiles/urls.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Profiles Django app urls."""


from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = "profiles"
urlpatterns = [
    path("", views.ProfileView.as_view(), name="profile"),
    # path('password/', views.password_change, name='password_change'),
    # path('password/done/', views.password_change_done, name='password_change_done'),
    path(
        "password/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="profiles/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="profiles/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profiles/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "signin/",
        auth_views.LoginView.as_view(template_name="profiles/signin.html"),
        name="signin",
    ),
    path(
        "signout/",
        auth_views.LogoutView.as_view(template_name="profiles/signout.html"),
        name="signout",
    ),
]

computer/urls.py
# -*- coding: utf-8 -*-
"""computer URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

computer/computer/views.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Computer Django app views."""

import json
import numpy as np

from django.db.models import Count
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseNotAllowed
from django.utils import timezone, translation
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django_markdowns.templatetags.markdowns import md
from intents import intents
from profiles.models import NLURequest
from texts.models import Answer, Attribute

from .nlu_models import NLUModel


@csrf_exempt
def markdown(request):
    """Handels GET/POST request for markdown.

    GET/POST parameters:
        text: the text to process
    """
    if request.method not in ["GET", "POST"]:
        return HttpResponseNotAllowed(["GET", "POST"])

    params = request.POST.copy() if request.method == "POST" else request.GET.copy()
    if "application/json" == request.META.get("CONTENT_TYPE"):
        params.update(json.loads(request.body.decode("utf-8")))

    if "text" in params:
        text = params.pop("text")[0].lower()
    else:
        return HttpResponseBadRequest('The parameter "text" was not given.')

    return JsonResponse({"text": md(text)})


@csrf_exempt
def nlu(request):
    """Handels POST request for nlu.

    POST parameters:
        text: the text to do the nlu for
    """
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    params = request.POST.copy()
    if "application/json" == request.META.get("CONTENT_TYPE"):
        params.update(json.loads(request.body.decode("utf-8")))

    nlu_request = NLURequest.objects.create(
        user=request.user if request.user.is_authenticated else None,
        params=params.dict(),
    )

    if "text" in params:
        text = params.pop("text")[0].lower()
    else:
        return HttpResponseBadRequest('The parameter "text" was not given.')

    try:
        model = NLUModel()
        outs = model.predict(text)

        translation.activate(outs["language"]["name"])
        request.LANGUAGE_CODE = translation.get_language()

        nlu_request.nlu_model_output = outs
        nlu_request.save()

        fn = getattr(intents, outs["intent"]["name"])
        properties = fn(
            text=text,
            language=outs["language"]["name"],
            user_agent=request.headers.get("User-Agent"),
            **outs["entities"]
        )
        nlu_request.intent_output = properties
        nlu_request.save()

        attributes = []
        for k, v in properties.items():
            attrs = Attribute.objects.filter(key=k)
            if attrs.count() > 1:
                if attrs.filter(value=v).exists():
                    attributes.append(attrs.filter(value=v)[0].pk)
                else:
                    attributes.append(attrs.filter(value=None)[0].pk)
            elif attrs.count() == 1:
                attributes.append(attrs[0].pk)

        answer = Answer.objects.annotate(num_attrs=Count("attributes")).filter(
            intents__name=outs["intent"]["name"],
            num_attrs=len(attributes),
            language=outs["language"]["name"],
        )
        for attribute in attributes:
            answer = answer.filter(attributes__id=attribute)

        if answer.count() >= 1:
            answer = np.random.choice(answer)
        else:
            answer = Answer.objects.filter(
                intents__name="fallback", language=request.LANGUAGE_CODE
            ).order_by("?")[:1][0]

        nlu_request.answer = answer.text % properties
        nlu_request.save()
        return JsonResponse(
            {
                "response_date": timezone.now().strftime("%Y-%m-%dT%H:%M:%S:%f%z"),
                "intent": outs["intent"]["name"],
                "certainty": outs["intent"]["p"],
                "replies": [md(answer.text % properties)],
            }
        )
    except Exception as e:
        text = _("An error occured while processing your request.")
        nlu_request.answer = text + " " + str(e)
        nlu_request.save()
        return JsonResponse(
            {
                "response_date": timezone.now().strftime("%Y-%m-%dT%H:%M:%S:%f%z"),
                "intent": "error",
                "certainty": 1.0,
                "replies": [text, str(e)],
            }
        )

computer/computer/templates/base.html
{% load django_html_utils i18n static %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="shortcut icon" href="{% static "images/icon.png" %}"/>
        {% django_html_utils_css %}
        {% django_html_utils_js %}
        <link rel="stylesheet" media="all" href="{% static "css/computer.css" %}"/>
        <script async src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS_CHTML"></script>
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
                config: ["MMLorHTML.js"],
                jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
                extensions: ["MathMenu.js", "MathZoom.js"]
            });
        </script>
        <title>{% block title %}computer{% endblock %}</title>
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        {% block navigation %}
            <nav class="navbar fixed-top navbar-expand-lg bg-white">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url "chat" %}">
                        <img alt="Brand" src="{% static "images/icon.png" %}" style="margin-top: -5px; height: 30px; display: inline-block;"/> computer
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent" role="navbar">
                        <ul class="navbar-nav me-auto">
                            {% if user.is_authenticated %}
                            {% else %}
                            {% endif %}
                        </ul>

                        {% if user.is_authenticated %}
                            <ul class="navbar-nav">
                                {% url "profiles:index" as profiles_index_url %}
                                <li class="nav-item dropdown{% if request.path|startswith:profiles_index_url %} active{% endif %}">
                                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {% if user.profile.avatar %}
                                           <!--% avatar size=26 classes="image-rounded" % -->
                                        {% else %}
                                            <b>{{ user.get_short_name }}</b>
                                        {% endif %}
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        {% url "profiles:profile" as profiles_profile_url %}
                                        <li>
                                            <a href="{{ profiles_profile_url }}" class="dropdown-item{% if request.path|startswith:profiles_profile_url %} active{% endif %}">
                                                {% translate "Profile" %}
                                                {% if request.path|startswith:profiles_profile_url %}<span class="sr-only">(current)</span>{% endif %}
                                            </a>
                                        </li>
                                        {% if user.is_staff %}
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="{% url "admin:index" %}">{% translate "Admin" %}</a>
                                        {% endif %}
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <form id="logout-form" method="post" action="{% url 'profiles:signout' %}">
                                                {% csrf_token %}
                                                <button type="submit" class="dropdown-item">{% translate 'Sign out' %}</button>
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        {% else %}
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="{% url "profiles:signin" %}?next={{ request.path }}" class="btn btn-outline-primary" role="button">{% translate "Sign in" %}</a>
                                </li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </nav>
        {% endblock %}
        <div class="container-fluid">
            {% block container %}
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                {% block breadcrumbs %}{% endblock %}
                            </ol>
                        </nav>
                        {% messages %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            {% endblock %}
        </div>
    </body>
</html>