computer/computer/urls.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""
URL configuration for computer project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView, TemplateView


admin.site.site_header = _("computer administration")


urlpatterns = [
    path("", TemplateView.as_view(template_name="computer/chat.html"), name="chat"),
    path("admin/", admin.site.urls),
    path("api/", include("computer.api_urls")),
    path("profiles/", include("profiles.urls")),
    path("favicon.ico", RedirectView.as_view(url="/static/images/icon.png")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

computer/profiles/urls.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Profiles Django app urls."""


from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views


app_name = "profiles"
urlpatterns = [
    path("", views.ProfileView.as_view(), name="profile"),
    # path('password/', views.password_change, name='password_change'),
    # path('password/done/', views.password_change_done, name='password_change_done'),
    path(
        "password/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="profiles/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="profiles/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="profiles/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "signin/",
        auth_views.LoginView.as_view(template_name="profiles/signin.html"),
        name="signin",
    ),
    path(
        "signout/",
        auth_views.LogoutView.as_view(template_name="profiles/signout.html"),
        name="signout",
    ),
]

computer/urls.py
# -*- coding: utf-8 -*-
"""computer URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

computer/profiles/models.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Profiles Django app models."""

import os

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .user_manager import UserManager


def default_unique_visitor_id():
    """Create an unique visitor ID."""
    return "".join(["%02x" % h for h in os.urandom(8)])


def get_avatar_image_path(instance: models.Model, filename: str) -> str:
    """Get image path."""
    return os.path.join(
        "profiles",
        "avatar",
        instance.user.unique_visitor_id + os.path.splitext(filename)[1],
    )


class User(AbstractBaseUser, PermissionsMixin):
    """User."""

    objects = UserManager()
    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated at"))

    email = models.EmailField(unique=True, verbose_name=_("Email"))
    first_name = models.CharField(max_length=256, verbose_name=_("First name"))
    last_name = models.CharField(
        max_length=256, blank=True, null=True, verbose_name=_("Last name")
    )
    date_joined = models.DateTimeField(
        default=timezone.now, verbose_name=_("Date joined")
    )
    is_staff = models.BooleanField(
        _("Staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this site."),
    )
    is_active = models.BooleanField(
        _("Active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. Unselect this "
            + "instead of deleting accounts."
        ),
    )
    unique_visitor_id = models.CharField(
        max_length=16,
        default=default_unique_visitor_id,
        unique=True,
        verbose_name=_("Unique visitor ID"),
    )

    def __str__(self) -> str:
        """Name."""
        return self.get_short_name()

    def get_full_name(self) -> str:
        """Get full name of a user."""
        return ("%s %s" % (self.first_name, self.last_name)).strip()

    def get_short_name(self) -> str:
        """Get short name of the user."""
        return self.first_name

    class Meta:
        """Meta."""

        ordering = ("email",)
        verbose_name = _("User")
        verbose_name_plural = _("Users")


class Profile(models.Model):
    """Profile."""

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated at"))

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        models.CASCADE,
        related_name="profile",
        verbose_name=_("User"),
    )
    avatar = models.ImageField(
        upload_to=get_avatar_image_path,
        max_length=150,
        verbose_name=_("Avatar"),
    )
    preferences = models.JSONField(default=dict, verbose_name=_("Preferences"))

    def __str__(self) -> str:
        """Name."""
        return self.user.get_short_name()

    class Meta:
        """Meta."""

        ordering = ("user",)
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")


class NLURequest(models.Model):
    """NLU request."""

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated at"))

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.CASCADE,
        blank=True,
        null=True,
        related_name="nlu_requests",
        verbose_name=_("User"),
    )
    params = models.JSONField(default=dict, verbose_name=_("Request parameters"))
    nlu_model_output = models.JSONField(
        default=dict, verbose_name=_("NLU model output")
    )
    intent_output = models.JSONField(default=dict, verbose_name=_("Intent output"))
    answer = models.TextField(verbose_name=_("Answer"))

    def __str__(self) -> str:
        """Name."""
        return (
            f"{self.user.get_short_name() if self.user else 'Anonymous'} "
            + "{self.updated_at}"
        )

    class Meta:
        """Meta."""

        ordering = ("user", "-updated_at")
        verbose_name = _("NLU request")
        verbose_name_plural = _("NLU requests")

computer/profiles/forms.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Profiles Django app forms."""

from django.contrib.auth import forms, get_user_model
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _


# class PasswordChangeForm(forms.PasswordChangeForm):
#     def __init__(self, *args, **kwargs):
#         super(PasswordChangeForm, self).__init__(*args, **kwargs)
#         self.fields['new_password1'].help_text = \
#             mark_safe(self.fields['new_password1'].help_text)


# class SetPasswordForm(forms.SetPasswordForm):
#     def __init__(self, *args, **kwargs):
#         super(SetPasswordForm, self).__init__(*args, **kwargs)
#         self.fields['new_password1']. \
#             help_text = mark_safe(self.fields['new_password1'].help_text)


class UserChangeForm(forms.UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.fields["password"].help_text = mark_safe(self.fields["password"].help_text)

    class Meta(forms.UserChangeForm.Meta):
        model = get_user_model()
        fields = ("email", "password", "first_name", "last_name")


class UserCreationForm(forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields["password1"].help_text = mark_safe(
            self.fields["password1"].help_text
        )

    class Meta(forms.UserCreationForm.Meta):
        model = get_user_model()
        fields = ("email", "first_name")

computer/profiles/views.py
# Copyright (C) 2017-2025 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# Computer - personal assistant.
#
# This file is part of computer.
#
# computer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# computer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with computer. If not, see <http://www.gnu.org/licenses/>
"""Profiles Django app views."""

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from .forms import UserChangeForm


class ProfileView(LoginRequiredMixin, SuccessMessageMixin, generic.edit.UpdateView):
    """Profilei update view."""

    form_class = UserChangeForm
    model = get_user_model()
    success_url = reverse_lazy("profiles:profile")
    success_message = _("Your profile has been successfully updated.")

    def get_object(self, queryset=None):
        """Get object."""
        return self.request.user

computer/profiles/templates/profiles/password_reset_form.html
{% extends "base.html" %}
{% load django_html_utils i18n static %}


{% block content %}
<div class="row">
    <div class="col-md-4 offset-md-4 col-sm-6 offset-sm-3 d-flex justify-content-center">
        <div class="card card-login mx-auto mt-5">
            <h4 class="card-header">{% translate "computer" %}</h4>
            <div class="card-body">
                <p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>
                {% translate 'Reset my password' as password_reset_text %}
                {% form form=form submit_title=password_reset_text %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

computer/profiles/templates/profiles/signin.html
{% extends "base.html" %}
{% load django_html_utils i18n static %}

{% block extrahead %}{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-4 offset-4 d-flex justify-content-center">
                <p class="alert alert-danger">
                    {% blocktranslate trimmed with username=request.user.username %}You are authenticated as {{ username }}, but are not authorized to access this page. Would you like to login to a different account?{% endblocktranslate %}
                </p>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-4 offset-md-4 col-sm-6 offset-sm-3 d-flex justify-content-center">
                <div class="card card-login mx-auto mt-5">
                    <h4 class="card-header">{% translate "computer" %}</h4>
                    <div class="card-body">
                        {% if invalid %}
                            <div class="alert alert-danger">{% translate "Invalid e-mail or password" %}</div>
                        {% endif %}
                        <form action="{% url 'profiles:signin' %}" method="post" id="login-form">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" id="inputUsername" name="username" class="form-control" autocomplete="email webauthn" autofocus="autofocus" placeholder="{% translate "E-mail" %}">
                                <label for="inputUsername" class="form-label">{% translate "E-mail" %}:</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" id="inputPassword"  name="password" class="form-control" placeholder="{% translate "Password" %}">
                                <label for="inputPassword" class="form-label">{% translate "Password" %}:</label>
                            </div>
                            <div class="mb-3 text-center">
                                <input type="hidden" name="passkeys" id="passkeys">
                                <input type="hidden" name="next" value="{{ next }}">
                                <button class="btn btn-block btn-light" type="button" onclick="authn('login-form')">{% fa "key" %} {% translate "Login by passkey" %}</button>
                                <button class="btn btn-primary btn-block" type="submit">{% fa "right-to-bracket" %} {% translate "Login" %}</button>
                            </div>
                            <div class="mb-3 text-center">
                                <a href="{% url "profiles:password_reset" %}">{% translate "Password forgotten?" %}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

computer/profiles/templates/profiles/signout.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>{% trans "Thanks for spending some quality time with computer today." %}</h3>
        <p><a href="{% url "profiles:signin" %}">{% trans "Sign in again" %}</a></p>
    </div>
</div>
{% endblock %}

computer/profiles/templates/profiles/user_form.html
{% extends "base.html" %}
{% load django_html_utils i18n %}


{% block title %}Profile • computer{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        {% translate "Save" as save_trans %}
        {% url "profiles:profile" as form_url %}
        {% form form=form url=form_url submit_title=save_trans %}
    </div>
</div>
{% endblock%}